[book]
authors = ["hashed.systems"]
language = "en"
multilingual = false
src = "src"
title = "Document Graph"
default-theme = "navy"

[preprocessor.plantuml]
[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/hashed-io"
git-repository-icon = "fa-github"